<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{5538f496-a75c-45f1-9bad-d338e8535694}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbStateMachine : FB_StateMachine;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
fbStateMachine();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="6" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>